### ISSUE TITLE
mosaic: killing the process won't kill the service (if any)

### ISSUE THREAD

**Issue by 0cv** [sst/ion#712]
1- I start mosaic with `sst mosaic` 

2- stripped down `sst.config.ts` with a Cluster:
```
const cluster = new sst.aws.Cluster("Ecs", { vpc });
cluster.addService("Service", {
  dev: {
    command: "npm run local:service",
  },
  ...
}
```

3- stripped down `package.json`:
```
{
  "scripts": {
    "local:service": "PORT=8080 wgo run -cd service ."
     ...
  },
}
```

The `wgo` service stays active (forever) when I kill `sst mosaic` (through e.g. ctrl + c)

**Comment by thdxr** [comment]
should be fixed in 0.1.2

**Comment by 0cv** [comment]
@thdxr I'm running the latest version as of today (0.1.8) and I still see my service running after stopping the Mosaic process
